<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.6" />
    <PackageReference Include="LiveCharts.WinForms" Version="0.9.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SSE.BLL\SSE.BLL.csproj" />
    <ProjectReference Include="..\SSE.Entidades\SSE.Entidades.csproj" />
  </ItemGroup>

</Project>